/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kp2.gradle;

import static com.diogonunes.jcolor.Ansi.colorize;
import static com.diogonunes.jcolor.Attribute.*;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello Everyone!");

        System.out.println(colorize("DevOps Project Week 2!", YELLOW_TEXT(), MAGENTA_BACK()));
        System.out.println("\n");
    }
}