/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kp2.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    System.out.println("Hello Everybody!");
}
